name: CI

# For all pushes to the main branch run the tests and push the image to the
# GitHub registry under an edge tag so we can use it for the nightly
# integration tests
on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest-server
    uses: https://git.bktus.com/pub/workflows/.gitea/workflows/docker-build.yaml@v0.0.3
    with:
      image: gpgfrontend/manual
      registry: git.stdv.de
    secrets:
      REGISTRY_USER: ${{ secrets.DOCKER_USERNAME }}
      REGISTRY_PASS: ${{ secrets.DOCKER_PASSWORD }}
